services:
  web:
    build: .
    environment:
      APP_ROLE: shell
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - celery
    networks:
      - dokploy-network

  celery:
    build: .
    command: celery
    environment:
      APP_ROLE: celery
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - dokploy-network

  beat:
    build: .
    command: beat
    environment:
      APP_ROLE: beat
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
