services:
  web:
    image: ${DOCKERHUB_USERNAME}/sakeena-web:latest
    environment:
      APP_ROLE: web
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - celery
    networks:
      - dokploy-network

  celery:
    image: ${DOCKERHUB_USERNAME}/sakeena-web:latest
    environment:
      APP_ROLE: celery
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - dokploy-network

  beat:
    image: ${DOCKERHUB_USERNAME}/sakeena-web:latest
    environment:
      APP_ROLE: beat
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
