from datetime import date, datetime, timedelta
from django.utils.timezone import make_aware


def generate_slots_for_rule(rule, weeks=8):
    """
    Generate AvailableTimeslot rows for `rule` covering the next `weeks` weeks.
    Splits the rule's time window into session_duration_minutes chunks.
    Uses get_or_create so it's safe to call multiple times (idempotent).
    All datetimes are stored as UTC-aware.
    """
    from .models import AvailableTimeslot

    today = date.today()
    start_date = max(today, rule.valid_from)
    end_date = today + timedelta(weeks=weeks)
    if rule.valid_until:
        end_date = min(end_date, rule.valid_until)

    duration = timedelta(minutes=rule.session_duration_minutes)
    created_count = 0

    current_day = start_date
    while current_day <= end_date:
        if current_day.weekday() == rule.weekday:
            window_start = make_aware(datetime.combine(current_day, rule.start_time))
            window_end = make_aware(datetime.combine(current_day, rule.end_time))

            slot_start = window_start
            while slot_start + duration <= window_end:
                slot_end = slot_start + duration
                _, created = AvailableTimeslot.objects.get_or_create(
                    consultation=rule.consultation,
                    scheduled_start=slot_start,
                    scheduled_end=slot_end,
                    defaults={"recurring_rule": rule},
                )
                if created:
                    created_count += 1
                slot_start += duration

        current_day += timedelta(days=1)

    return created_count


def delete_future_unbooked_slots(rule):
    """Delete future unbooked slots generated by this rule."""
    from .models import AvailableTimeslot
    from django.utils.timezone import now

    AvailableTimeslot.objects.filter(
        recurring_rule=rule,
        scheduled_start__gte=now(),
        is_booked=False,
    ).delete()
