# Generated by Django 6.0.2 on 2026-03-30 05:30

import books.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Book Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[800, 1000], upload_to='books/covers/')),
                ('isbn', models.CharField(help_text='10 or 13 digit ISBN', max_length=20, unique=True, validators=[books.validators.validate_isbn])),
                ('language', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('number_of_pages', models.PositiveIntegerField()),
                ('sample_file', models.FileField(blank=True, null=True, upload_to='books/samples/', validators=[books.validators.validate_pdf])),
                ('video_url', models.URLField(blank=True, help_text='Link to a book trailer or intro video', null=True)),
                ('has_physical', models.BooleanField(default=False)),
                ('physical_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_count', models.PositiveIntegerField(default=0)),
                ('has_digital', models.BooleanField(default=False)),
                ('digital_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.bookcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1200, 800], upload_to='books/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='books.book')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
