# Generated by Django 6.0.2 on 2026-03-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags for the book'),
        ),
    ]
