# Generated by Django 6.0.2 on 2026-03-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_designation',
            field=models.CharField(default='Clinical Psychologist', max_length=255),
            preserve_default=False,
        ),
    ]
