# Generated by Django 6.0.2 on 2026-04-13 08:43

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_author_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='digital_file',
            field=models.FileField(blank=True, help_text='Full PDF delivered to buyers. Never exposed publicly.', null=True, upload_to='books/digital/', validators=[books.validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='book',
            name='sample_file',
            field=models.FileField(blank=True, help_text='Free preview PDF visible to everyone.', null=True, upload_to='books/samples/', validators=[books.validators.validate_pdf]),
        ),
    ]
