# Generated by Django 6.0.2 on 2026-04-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_digital_file_alter_book_sample_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='interior_pdf_url',
            field=models.URLField(blank=True, help_text='Publicly accessible URL of the print-ready interior PDF for Lulu.', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='lulu_pod_package_id',
            field=models.CharField(blank=True, help_text='Lulu pod_package_id encoding paper size, binding, color. e.g. 0600X0900BWSTDSS060UW444MXX', max_length=100, null=True),
        ),
    ]
