# Generated by Django 6.0.2 on 2026-04-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_lulu_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='interior_pdf_url',
        ),
    ]
