# Generated by Django 6.0.2 on 2026-04-23 10:45

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_interior_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lulu_cover_pdf',
            field=models.FileField(blank=True, help_text="Print-ready cover PDF for Lulu (front + spine + back with bleed). Must be a PDF — JPEG/WebP images are NOT accepted by Lulu. Generate using Lulu's cover generator or a design tool.", null=True, upload_to='books/lulu_covers/', validators=[books.validators.validate_pdf]),
        ),
    ]
