# Generated by Django 6.0.2 on 2026-04-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_lulu_cover_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='lulu_pod_package_id',
            field=models.CharField(blank=True, help_text='Lulu pod_package_id in dot-separated format: TrimSize.Color.Quality.Binding.Paper.CoverFinish — e.g. 0827X1169.FC.STD.PB.060UW444.MXX', max_length=100, null=True),
        ),
    ]
