# Generated by Django 6.0.2 on 2026-04-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_lulu_pod_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of interior pages. Required for Lulu shipping cost calculation.', null=True),
        ),
    ]
