# Generated by Django 6.0.2 on 2026-04-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_page_count_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number_of_pages',
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of interior pages. Also used for Lulu shipping cost calculation.'),
            preserve_default=False,
        ),
    ]
