# Generated by Django 6.0.2 on 2026-04-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_subscribed_to_newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
