# Generated by Django 6.0.2 on 2026-04-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_is_subscribed_to_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='offers_consultations',
            field=models.BooleanField(default=False, help_text='Whether this teacher offers consultation sessions'),
        ),
    ]
