# Generated by Django 6.0.2 on 2026-04-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_phone_location_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='consultation_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The rate the teacher earns per consultation session (payout rate). This is separate from the student-facing price set on each Consultation.', max_digits=10),
        ),
    ]
