# Generated by Django 6.0.2 on 2026-03-14 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_studentprofile_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='General Consultation', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('standard_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard price per session', max_digits=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='accounts.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sessions', models.PositiveIntegerField(help_text='The number of sessions a student must purchase to receive a discount')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage applied when conditions are met', max_digits=5)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='consultations.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTimeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='consultations.consultation')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sessions_purchased', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_slots', models.ManyToManyField(related_name='purchases', to='consultations.availabletimeslot')),
                ('bundle_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.bundle')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
