# Generated by Django 6.0.2 on 2026-04-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultationpurchase_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletimeslot',
            name='zoom_join_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='availabletimeslot',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='availabletimeslot',
            name='zoom_start_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
