# Generated by Django 6.0.2 on 2026-04-11 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_availabletimeslot_zoom_join_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='availabletimeslot',
            index=models.Index(fields=['consultation', 'is_booked'], name='ts_consult_booked_idx'),
        ),
        migrations.AddIndex(
            model_name='availabletimeslot',
            index=models.Index(fields=['day', 'is_booked'], name='ts_day_booked_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationpurchase',
            index=models.Index(fields=['student', 'status'], name='purchase_stu_status_idx'),
        ),
    ]
