# Generated by Django 6.0.2 on 2026-04-12 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_availabletimeslot_ts_consult_booked_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(help_text='Start of availability window')),
                ('end_time', models.TimeField(help_text='End of availability window')),
                ('session_duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration of each individual session slot in minutes')),
                ('valid_from', models.DateField(help_text='First date this rule applies from')),
                ('valid_until', models.DateField(blank=True, help_text='Last date this rule applies (leave blank for ongoing)', null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='consultations.consultation')),
            ],
            options={
                'verbose_name_plural': 'Recurring availabilities',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='availabletimeslot',
            name='recurring_rule',
            field=models.ForeignKey(blank=True, help_text='Set if this slot was auto-generated from a recurring rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_slots', to='consultations.recurringavailability'),
        ),
    ]
