# Generated by Django 6.0.2 on 2026-04-22 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_timeslot_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests_as_old', to='consultations.availabletimeslot')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='consultations.consultationpurchase')),
                ('requested_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests_as_new', to='consultations.availabletimeslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
