# Generated by Django 6.0.2 on 2026-04-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation_type',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='stripe_customer_id',
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='stripe_reference',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID.', max_length=255, null=True),
        ),
    ]
