# Generated by Django 6.0.3 on 2026-03-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration_in_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration in minutes'),
        ),
    ]
