# Generated by Django 6.0.3 on 2026-03-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_duration_in_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='num_lessons',
        ),
    ]
