# Generated by Django 6.0.2 on 2026-03-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
            preserve_default=False,
        ),
    ]
