# Generated by Django 6.0.2 on 2026-03-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_total_hours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CourseCategory',
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
    ]
