# Generated by Django 6.0.2 on 2026-04-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_scholarship_created_at_scholarship_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='scholarships/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='courses.scholarship')),
            ],
        ),
    ]
