# Generated by Django 6.0.2 on 2026-03-29 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_category_coursecategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duration',
            new_name='duration_in_weeks',
        ),
    ]
