# Generated by Django 6.0.2 on 2026-04-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_scholarshipdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='personal_statement',
        ),
    ]
