# Generated by Django 6.0.2 on 2026-04-11 05:36

import uuid
from django.db import migrations, models
from django.utils.text import slugify


def populate_course_slugs(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    seen = set()
    for course in Course.objects.all():
        base = slugify(course.title) or str(course.pk)
        slug = base
        while slug in seen or Course.objects.filter(slug=slug).exclude(pk=course.pk).exists():
            slug = f"{base}-{uuid.uuid4().hex[:6]}"
        course.slug = slug
        seen.add(slug)
        course.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, default='', unique=False, db_index=False),
        ),
        migrations.RunPython(populate_course_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
