# Generated by Django 6.0.2 on 2026-04-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Start time for live sessions (UTC)', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='zoom_join_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='zoom_start_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('external_link', 'External Link'), ('live', 'Live Session')], max_length=15),
        ),
    ]
