# Generated by Django 6.0.2 on 2026-04-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_enrollment_enrollment_user_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='bunny_video_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='bunny_video_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
