# Generated by Django 6.0.2 on 2026-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_add_bunny_video_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_released',
            field=models.BooleanField(default=False, help_text='Non-live lessons: mark as released to unlock for enrolled students.'),
        ),
    ]
