# Generated by Django 6.0.2 on 2026-04-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_lesson_is_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bunny_video_id',
            field=models.CharField(blank=True, default='', help_text='Bunny Stream video ID for the course promo/intro video.', max_length=100),
        ),
    ]
