# Generated by Django 6.0.2 on 2026-04-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_bunny_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='bunny_video_id',
        ),
    ]
