# Generated by Django 6.0.2 on 2026-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_assignmentsubmission_quizattempt_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='zoom_host_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
