# Generated by Django 6.0.2 on 2026-04-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_lesson_zoom_host_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_content',
        ),
    ]
