# Generated by Django 6.0.2 on 2026-04-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_video_content_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_content',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
