# Generated by Django 6.0.2 on 2026-04-21 05:38

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_restore_video_content_as_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[800, 600], upload_to='courses/thumbnails/'),
        ),
    ]
