# Generated by Django 6.0.2 on 2026-04-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_downloadable',
            field=models.BooleanField(default=False, help_text='If True, students can download the document file.'),
        ),
    ]
