# Generated by Django 6.0.2 on 2026-05-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_lesson_is_downloadable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['display_order', '-id']},
        ),
        migrations.AddField(
            model_name='course',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls the display order of courses. Lower numbers appear first.'),
        ),
    ]
