# Generated by Django 6.0.2 on 2026-04-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteannouncement',
            old_name='link',
            new_name='cta_link',
        ),
        migrations.RenameField(
            model_name='siteannouncement',
            old_name='big_text',
            new_name='main_title',
        ),
        migrations.RenameField(
            model_name='siteannouncement',
            old_name='small_text',
            new_name='message',
        ),
        migrations.AddField(
            model_name='siteannouncement',
            name='badges',
            field=models.JSONField(blank=True, default=list, help_text="List of campaign badge strings, e.g. ['New', 'Limited']"),
        ),
        migrations.AddField(
            model_name='siteannouncement',
            name='cta_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='siteannouncement',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text="List of highlight strings, e.g. ['Free shipping', '24/7 support']"),
        ),
        migrations.AddField(
            model_name='siteannouncement',
            name='title_prefix',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
