# Generated by Django 6.0.2 on 2026-04-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_about', models.TextField(blank=True)),
                ('long_about', models.TextField(blank=True, help_text='Supports rich HTML content.')),
                ('privacy_policy', models.TextField(blank=True, help_text='Supports rich HTML content.')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Supports rich HTML content.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
