# Generated by Django 6.0.2 on 2026-04-06 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('course_purchase', 'Course Purchase Confirmation'), ('book_purchase', 'Book Purchase Confirmation'), ('blog_approved', 'Blog Post Approved'), ('blog_rejected', 'Blog Post Rejected'), ('newsletter', 'Newsletter')], max_length=50, unique=True)),
                ('sendgrid_template_id', models.CharField(help_text='SendGrid dynamic template ID (starts with d-)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional notes about this template mapping')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_template_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template Config',
                'verbose_name_plural': 'Email Template Configs',
                'ordering': ['purpose'],
            },
        ),
    ]
