# Generated by Django 6.0.2 on 2026-04-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0002_alter_emailtemplateconfig_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplateconfig',
            name='purpose',
            field=models.CharField(choices=[('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('course_purchase', 'Course Purchase Confirmation'), ('bundle_purchase', 'Bundle Purchase Confirmation'), ('consultation_purchase', 'Consultation Purchase Confirmation'), ('book_purchase', 'Book Purchase Confirmation'), ('blog_approved', 'Blog Post Approved'), ('blog_rejected', 'Blog Post Rejected'), ('newsletter', 'Newsletter'), ('certificate_issued', 'Certificate Issued')], max_length=50, unique=True),
        ),
    ]
