# Generated by Django 6.0.2 on 2026-04-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_user_idx_order_order_user_status_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='not_applicable', max_length=20),
        ),
    ]
