# Generated by Django 6.0.2 on 2026-04-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_unified_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='lulu_print_job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
