# Generated by Django 6.0.2 on 2026-04-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_lulu_print_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(help_text="ISO 3166-1 alpha-2 country code (e.g. 'US', 'AE', 'KW')", max_length=2),
        ),
    ]
