# Generated by Django 6.0.2 on 2026-03-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='redirect_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
