# Generated by Django 6.0.2 on 2026-04-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_door_redirect_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='icon',
            field=models.FileField(upload_to='doors/icons/'),
        ),
    ]
